platform :'ios','9.0'
target 'OnTheWay' do
  pod 'MBProgressHUD'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'PPNetworkHelper'
  pod 'YSCategorys'
  pod 'STPopup'
  pod 'SDCycleScrollView'
  pod 'DACircularProgress'
  pod 'TZImagePickerController'
  pod 'BaiduMapKit' #百度地图SDK
end

