platform :'ios','9.0'
target 'MCYProject' do
  pod 'MBProgressHUD'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'YSCategorys'
  #pod 'STPopup'
  #pod 'SDCycleScrollView'
  #pod 'TZImagePickerController'
  #pod 'PPNetworkHelper'
  #pod 'DACircularProgress'
  #pod 'BaiduMapKit' #百度地图SDK
end

